apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-app
spec:
  selector:
    matchLabels:
      app: greetings-app
  replicas: 1
  template:
    metadata:
      labels:
        app: greetings-app
    spec:
      containers:
        - name: main
          image: patnaikshekhar/template-sample-app:0.1.0
